# Generated by Django 5.1.1 on 2024-09-10 03:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=50)),
                ('asset_description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('filetype', models.CharField(max_length=50)),
                ('uploaddate', models.CharField(max_length=50)),
                ('assettype', models.CharField(max_length=50)),
                ('asset', models.ImageField(upload_to='uploads/assets/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.category')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('timestamp', models.DateField(default=datetime.datetime.today)),
                ('downloadstatus', models.BooleanField(default=False)),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assets')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.designer')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assets')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.designer')),
            ],
        ),
    ]
