# Generated by Django 5.0.7 on 2024-09-18 07:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='user_name',
        ),
        migrations.AddField(
            model_name='designer',
            name='password1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='password2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='username',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=50)),
                ('asset_description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('filetype', models.CharField(max_length=50)),
                ('uploaddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('assettype', models.CharField(max_length=50)),
                ('asset_image', models.ImageField(upload_to='uploads/assets/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.category')),
            ],
        ),
        migrations.AddField(
            model_name='download',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='assets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
    ]
